"""The research paper remains buildable, source-audited, and machine-numbered.

These tests replaced an earlier set that checked the paper *admitted* to being
unfinished. That guard was right for a scaffold written before there were
results; it is meaningless now that the sections are written, and leaving it in
place would have meant deleting a failing test at the moment it stopped being
enforceable. What replaces it enforces the rule the finished paper actually
keeps: no headline number is typed into the prose.
"""

from __future__ import annotations

import csv
import re
from pathlib import Path

from popmodel import paths

PAPER = paths.REPO_ROOT / "paper"
GENERATED = PAPER / "generated" / "results_macros.tex"

#: Values that would be embarrassing to find hard-coded, because they are this
#: project's own results rather than a figure quoted from the literature.
HEADLINE_MACROS = (
    "LadderBenchmark", "LadderMainstream", "LadderNamedGroups", "LadderPressure",
    "LadderMainstreamGain", "LadderPressureLoss", "BoundaryPaired",
    "BoundaryDeterministic", "BoundaryFloor", "BoundaryCeiling",
    "RaceSelectionEffect", "RaceTwentyOneFifty", "ExtensionTwentyOneFifty",
    "WidthFertility", "WidthMechanism", "ComparatorTwentyOneFifty",
)

#: Standard LaTeX commands that also match the result-macro shape.
STANDARD_COMMANDS = frozenset({"LaTeX", "TeX", "LaTeXe"})


def prose_files() -> list[Path]:
    """Section and appendix sources, which is where prose numbers would hide."""
    return sorted((PAPER / "sections").glob("*.tex")) + sorted(
        (PAPER / "appendices").glob("*.tex")
    )


def defined_macros() -> dict[str, str]:
    text = GENERATED.read_text(encoding="utf-8")
    return {
        name: value.strip()
        for name, value in re.findall(
            r"\\newcommand\{\\([A-Za-z]+)\}\s*\{(.*?)\}\s*$", text, re.MULTILINE
        )
    }


def test_main_manuscript_includes_every_declared_section():
    main = (PAPER / "main.tex").read_text(encoding="utf-8")
    section_files = sorted((PAPER / "sections").glob("*.tex"))
    appendix_files = sorted((PAPER / "appendices").glob("*.tex"))
    assert len(section_files) >= 9
    for path in section_files + appendix_files:
        relative = path.relative_to(PAPER).with_suffix("").as_posix()
        assert f"\\input{{{relative}}}" in main


def test_every_result_macro_used_in_the_prose_is_defined():
    """A macro that is used but undefined compiles to nothing, silently."""
    available = defined_macros()
    assert available, "the generated macro file is empty; run build_paper_results.py"
    for path in prose_files():
        used = set(re.findall(r"\\([A-Z][A-Za-z]+)\{\}", path.read_text(encoding="utf-8")))
        missing = sorted(used - set(available) - STANDARD_COMMANDS)
        assert not missing, f"{path.name} uses undefined macros: {missing}"


def test_headline_results_are_macros_rather_than_typed_numbers():
    """The rule this directory exists to keep, checked rather than asserted.

    A number typed into prose stops tracking the model the moment the model is
    rerun, and nothing about the document will say so. Each headline value is
    read back out of the generated macros and searched for as a literal.
    """
    available = defined_macros()
    for name in HEADLINE_MACROS:
        assert name in available, f"{name} is no longer generated"
        literal = available[name].replace("\\%", "").strip()
        pattern = re.compile(rf"(?<![\d.]){re.escape(literal)}(?![\d.])")
        for path in prose_files():
            hits = pattern.findall(path.read_text(encoding="utf-8"))
            assert not hits, (
                f"{path.name} contains the literal {literal!r}, which is the "
                f"value of \\{name}. Use the macro so the prose follows the model."
            )


def test_generated_files_are_not_hand_edited():
    for path in (GENERATED, PAPER / "generated" / "parameter_table.tex"):
        assert path.exists(), f"{path.name} is missing; run build_paper_results.py"
        assert "Generated by scripts/build_paper_results.py" in path.read_text(
            encoding="utf-8"
        ), f"{path.name} lost its generated-file header"


def test_source_audit_is_complete_and_points_to_bibliography_entries():
    bibliography = (PAPER / "bibliography" / "references.bib").read_text(
        encoding="utf-8"
    )
    bib_keys = set(re.findall(r"@[a-zA-Z]+\{([^,]+),", bibliography))
    with (PAPER / "bibliography" / "source-audit.csv").open(
        newline="", encoding="utf-8"
    ) as stream:
        rows = list(csv.DictReader(stream))
    assert len(rows) >= 8
    assert all(row["claim"] and row["location"] and row["verified_on"] for row in rows)
    assert {row["citation_key"] for row in rows} <= bib_keys
    assert all(row["status"] == "verified" for row in rows)


def test_every_cited_work_is_audited():
    """A citation that never passed the audit is the failure mode to catch."""
    cited: set[str] = set()
    for path in prose_files():
        content = path.read_text(encoding="utf-8")
        for group in re.findall(r"\\cite[tp]?\{([^}]+)\}", content):
            cited.update(key.strip() for key in group.split(","))
    with (PAPER / "bibliography" / "source-audit.csv").open(
        newline="", encoding="utf-8"
    ) as stream:
        audited = {row["citation_key"] for row in csv.DictReader(stream)}
    assert cited <= audited, f"cited but not audited: {sorted(cited - audited)}"


def test_latex_sources_use_portable_ascii_text():
    for path in PAPER.rglob("*.tex"):
        content = path.read_text(encoding="utf-8")
        assert content.isascii(), f"non-ASCII text in {path.relative_to(paths.REPO_ROOT)}"
